### PR TITLE
Update Projects page

### PR DESCRIPTION
**Pull request by RashaMou**
Link updated Notion projects database to website

### CODE REVIEW

**Comment by OwenMatsuda** [comment]
I don't think the `yarn.lock` file should be updated here.

**Comment by OwenMatsuda** [comment]
Also are you able to include a screenshot of the changes made that show they are working?

**Comment by RashaMou** [comment]
> I don't think the `yarn.lock` file should be updated here.

Yep, removed

**Review by OwenMatsuda — APPROVED** [review]
Looks good to me :)

**Comment by RashaMou** [comment]
Thanks... I don't have the permission to merge this, would you mind merging if you do? If not I'll reach out to Tom.

**Pull request merged**
